services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - .:/app
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports: 
      - 6379:6379
volumes:
  postgres_data: